///////////////////////////////////////////////////////////////////////////////
// GameSpy ATLAS Competition System Source File
//
// NOTE: This is an auto-generated file, do not edit this file directly.
///////////////////////////////////////////////////////////////////////////////

/*#include <string.h>*/
#include "atlas_stalkercoppc_v1.h"

int atlas_rule_set_version = 1;

int ATLAS_GET_KEY(char* keyName)
{
    if (!keyName)
        return 0;

    if (!xr_strcmp("KEY_BestScore_KillsInRow", keyName))
        return KEY_BestScore_KillsInRow;
    if (!xr_strcmp("KEY_BestScore_KnifeKillsInRow", keyName))
        return KEY_BestScore_KnifeKillsInRow;
    if (!xr_strcmp("KEY_BestScore_BackstabsKillsInRow", keyName))
        return KEY_BestScore_BackstabsKillsInRow;
    if (!xr_strcmp("KEY_BestScore_HeadshotsKillsInRow", keyName))
        return KEY_BestScore_HeadshotsKillsInRow;
    if (!xr_strcmp("KEY_BestScore_EyeKillsInRow", keyName))
        return KEY_BestScore_EyeKillsInRow;
    if (!xr_strcmp("KEY_BestScore_BleedKillsInRow", keyName))
        return KEY_BestScore_BleedKillsInRow;
    if (!xr_strcmp("KEY_BestScore_ExplosiveKillsInRow", keyName))
        return KEY_BestScore_ExplosiveKillsInRow;
    if (!xr_strcmp("KEY_AwardMasscare", keyName))
        return KEY_AwardMasscare;
    if (!xr_strcmp("KEY_AwardMasscareLastRewardDate", keyName))
        return KEY_AwardMasscareLastRewardDate;
    if (!xr_strcmp("KEY_AwardParanoia", keyName))
        return KEY_AwardParanoia;
    if (!xr_strcmp("KEY_AwardParanoiaLastRewardDate", keyName))
        return KEY_AwardParanoiaLastRewardDate;
    if (!xr_strcmp("KEY_AwardOverwhelmingSuperiority", keyName))
        return KEY_AwardOverwhelmingSuperiority;
    if (!xr_strcmp("KEY_AwardOverwhelmingSuperiorityLastRewardDate", keyName))
        return KEY_AwardOverwhelmingSuperiorityLastRewardDate;
    if (!xr_strcmp("KEY_AwardBlitzkrieg", keyName))
        return KEY_AwardBlitzkrieg;
    if (!xr_strcmp("KEY_AwardBlitzkriegLastRewardDate", keyName))
        return KEY_AwardBlitzkriegLastRewardDate;
    if (!xr_strcmp("KEY_AwardDryVictory", keyName))
        return KEY_AwardDryVictory;
    if (!xr_strcmp("KEY_AwardDryVictoryLastRewardDate", keyName))
        return KEY_AwardDryVictoryLastRewardDate;
    if (!xr_strcmp("KEY_AwardMultichampion", keyName))
        return KEY_AwardMultichampion;
    if (!xr_strcmp("KEY_AwardMultichampionLastRewardDate", keyName))
        return KEY_AwardMultichampionLastRewardDate;
    if (!xr_strcmp("KEY_AwardMad", keyName))
        return KEY_AwardMad;
    if (!xr_strcmp("KEY_AwardMadLastRewardDate", keyName))
        return KEY_AwardMadLastRewardDate;
    if (!xr_strcmp("KEY_AwardAchillesHeel", keyName))
        return KEY_AwardAchillesHeel;
    if (!xr_strcmp("KEY_AwardAchillesHeelLastRewardDate", keyName))
        return KEY_AwardAchillesHeelLastRewardDate;
    if (!xr_strcmp("KEY_AwardFasterThanBullets", keyName))
        return KEY_AwardFasterThanBullets;
    if (!xr_strcmp("KEY_AwardFasterThanBulletsLastRewardDate", keyName))
        return KEY_AwardFasterThanBulletsLastRewardDate;
    if (!xr_strcmp("KEY_AwardHarvestTime", keyName))
        return KEY_AwardHarvestTime;
    if (!xr_strcmp("KEY_AwardHarvestTimeLastRewardDate", keyName))
        return KEY_AwardHarvestTimeLastRewardDate;
    if (!xr_strcmp("KEY_AwardSkewer", keyName))
        return KEY_AwardSkewer;
    if (!xr_strcmp("KEY_AwardSkewerLastRewardDate", keyName))
        return KEY_AwardSkewerLastRewardDate;
    if (!xr_strcmp("KEY_AwardDoubleShotDoubleKill", keyName))
        return KEY_AwardDoubleShotDoubleKill;
    if (!xr_strcmp("KEY_AwardDoubleShotDoubleKillLastRewardDate", keyName))
        return KEY_AwardDoubleShotDoubleKillLastRewardDate;
    if (!xr_strcmp("KEY_AwardClimber", keyName))
        return KEY_AwardClimber;
    if (!xr_strcmp("KEY_AwardClimberLastRewardDate", keyName))
        return KEY_AwardClimberLastRewardDate;
    if (!xr_strcmp("KEY_AwardOpener", keyName))
        return KEY_AwardOpener;
    if (!xr_strcmp("KEY_AwardOpenerLastRewardDate", keyName))
        return KEY_AwardOpenerLastRewardDate;
    if (!xr_strcmp("KEY_AwardToughy", keyName))
        return KEY_AwardToughy;
    if (!xr_strcmp("KEY_AwardToughyLastRewardDate", keyName))
        return KEY_AwardToughyLastRewardDate;
    if (!xr_strcmp("KEY_AwardInvincibleFury", keyName))
        return KEY_AwardInvincibleFury;
    if (!xr_strcmp("KEY_AwardInvincibleFuryLastRewardDate", keyName))
        return KEY_AwardInvincibleFuryLastRewardDate;
    if (!xr_strcmp("KEY_AwardOculist", keyName))
        return KEY_AwardOculist;
    if (!xr_strcmp("KEY_AwardOculistLastRewardDate", keyName))
        return KEY_AwardOculistLastRewardDate;
    if (!xr_strcmp("KEY_AwardLightingReflexes", keyName))
        return KEY_AwardLightingReflexes;
    if (!xr_strcmp("KEY_AwardLightingReflexesLastRewardDate", keyName))
        return KEY_AwardLightingReflexesLastRewardDate;
    if (!xr_strcmp("KEY_AwardSprinterStopper", keyName))
        return KEY_AwardSprinterStopper;
    if (!xr_strcmp("KEY_AwardSprinterStopperLastRewardDate", keyName))
        return KEY_AwardSprinterStopperLastRewardDate;
    if (!xr_strcmp("KEY_AwardMarksMan", keyName))
        return KEY_AwardMarksMan;
    if (!xr_strcmp("KEY_AwardMarksManLastRewardDate", keyName))
        return KEY_AwardMarksManLastRewardDate;
    if (!xr_strcmp("KEY_AwardPeaceAmbassador", keyName))
        return KEY_AwardPeaceAmbassador;
    if (!xr_strcmp("KEY_AwardPeaceAmbassadorLastRewardDate", keyName))
        return KEY_AwardPeaceAmbassadorLastRewardDate;
    if (!xr_strcmp("KEY_AwardDeadlyAccuracy", keyName))
        return KEY_AwardDeadlyAccuracy;
    if (!xr_strcmp("KEY_AwardDeadlyAccuracyLastRewardDate", keyName))
        return KEY_AwardDeadlyAccuracyLastRewardDate;
    if (!xr_strcmp("KEY_AwardRemembrance", keyName))
        return KEY_AwardRemembrance;
    if (!xr_strcmp("KEY_AwardRemembranceLastRewardDate", keyName))
        return KEY_AwardRemembranceLastRewardDate;
    if (!xr_strcmp("KEY_AwardAvenger", keyName))
        return KEY_AwardAvenger;
    if (!xr_strcmp("KEY_AwardAvengerLastRewardDate", keyName))
        return KEY_AwardAvengerLastRewardDate;
    if (!xr_strcmp("KEY_AwardCherub", keyName))
        return KEY_AwardCherub;
    if (!xr_strcmp("KEY_AwardCherubLastRewardDate", keyName))
        return KEY_AwardCherubLastRewardDate;
    if (!xr_strcmp("KEY_AwardDignity", keyName))
        return KEY_AwardDignity;
    if (!xr_strcmp("KEY_AwardDignityLastRewardDate", keyName))
        return KEY_AwardDignityLastRewardDate;
    if (!xr_strcmp("KEY_AwardStalkerFlair", keyName))
        return KEY_AwardStalkerFlair;
    if (!xr_strcmp("KEY_AwardStalkerFlairLastRewardDate", keyName))
        return KEY_AwardStalkerFlairLastRewardDate;
    if (!xr_strcmp("KEY_AwardLucky", keyName))
        return KEY_AwardLucky;
    if (!xr_strcmp("KEY_AwardLuckyLastRewardDate", keyName))
        return KEY_AwardLuckyLastRewardDate;
    if (!xr_strcmp("KEY_AwardBlackList", keyName))
        return KEY_AwardBlackList;
    if (!xr_strcmp("KEY_AwardBlackListLastRewardDate", keyName))
        return KEY_AwardBlackListLastRewardDate;
    if (!xr_strcmp("KEY_AwardSilentDeath", keyName))
        return KEY_AwardSilentDeath;
    if (!xr_strcmp("KEY_AwardSilentDeathLastRewardDate", keyName))
        return KEY_AwardSilentDeathLastRewardDate;
    if (!xr_strcmp("KEY_PlayerName", keyName))
        return KEY_PlayerName;

    return 0;
}

char* ATLAS_GET_KEY_NAME(int keyId)
{
    if (keyId <= 0)
        return "";

    if (keyId == KEY_BestScore_KillsInRow)
        return "KEY_BestScore_KillsInRow";
    if (keyId == KEY_BestScore_KnifeKillsInRow)
        return "KEY_BestScore_KnifeKillsInRow";
    if (keyId == KEY_BestScore_BackstabsKillsInRow)
        return "KEY_BestScore_BackstabsKillsInRow";
    if (keyId == KEY_BestScore_HeadshotsKillsInRow)
        return "KEY_BestScore_HeadshotsKillsInRow";
    if (keyId == KEY_BestScore_EyeKillsInRow)
        return "KEY_BestScore_EyeKillsInRow";
    if (keyId == KEY_BestScore_BleedKillsInRow)
        return "KEY_BestScore_BleedKillsInRow";
    if (keyId == KEY_BestScore_ExplosiveKillsInRow)
        return "KEY_BestScore_ExplosiveKillsInRow";
    if (keyId == KEY_AwardMasscare)
        return "KEY_AwardMasscare";
    if (keyId == KEY_AwardMasscareLastRewardDate)
        return "KEY_AwardMasscareLastRewardDate";
    if (keyId == KEY_AwardParanoia)
        return "KEY_AwardParanoia";
    if (keyId == KEY_AwardParanoiaLastRewardDate)
        return "KEY_AwardParanoiaLastRewardDate";
    if (keyId == KEY_AwardOverwhelmingSuperiority)
        return "KEY_AwardOverwhelmingSuperiority";
    if (keyId == KEY_AwardOverwhelmingSuperiorityLastRewardDate)
        return "KEY_AwardOverwhelmingSuperiorityLastRewardDate";
    if (keyId == KEY_AwardBlitzkrieg)
        return "KEY_AwardBlitzkrieg";
    if (keyId == KEY_AwardBlitzkriegLastRewardDate)
        return "KEY_AwardBlitzkriegLastRewardDate";
    if (keyId == KEY_AwardDryVictory)
        return "KEY_AwardDryVictory";
    if (keyId == KEY_AwardDryVictoryLastRewardDate)
        return "KEY_AwardDryVictoryLastRewardDate";
    if (keyId == KEY_AwardMultichampion)
        return "KEY_AwardMultichampion";
    if (keyId == KEY_AwardMultichampionLastRewardDate)
        return "KEY_AwardMultichampionLastRewardDate";
    if (keyId == KEY_AwardMad)
        return "KEY_AwardMad";
    if (keyId == KEY_AwardMadLastRewardDate)
        return "KEY_AwardMadLastRewardDate";
    if (keyId == KEY_AwardAchillesHeel)
        return "KEY_AwardAchillesHeel";
    if (keyId == KEY_AwardAchillesHeelLastRewardDate)
        return "KEY_AwardAchillesHeelLastRewardDate";
    if (keyId == KEY_AwardFasterThanBullets)
        return "KEY_AwardFasterThanBullets";
    if (keyId == KEY_AwardFasterThanBulletsLastRewardDate)
        return "KEY_AwardFasterThanBulletsLastRewardDate";
    if (keyId == KEY_AwardHarvestTime)
        return "KEY_AwardHarvestTime";
    if (keyId == KEY_AwardHarvestTimeLastRewardDate)
        return "KEY_AwardHarvestTimeLastRewardDate";
    if (keyId == KEY_AwardSkewer)
        return "KEY_AwardSkewer";
    if (keyId == KEY_AwardSkewerLastRewardDate)
        return "KEY_AwardSkewerLastRewardDate";
    if (keyId == KEY_AwardDoubleShotDoubleKill)
        return "KEY_AwardDoubleShotDoubleKill";
    if (keyId == KEY_AwardDoubleShotDoubleKillLastRewardDate)
        return "KEY_AwardDoubleShotDoubleKillLastRewardDate";
    if (keyId == KEY_AwardClimber)
        return "KEY_AwardClimber";
    if (keyId == KEY_AwardClimberLastRewardDate)
        return "KEY_AwardClimberLastRewardDate";
    if (keyId == KEY_AwardOpener)
        return "KEY_AwardOpener";
    if (keyId == KEY_AwardOpenerLastRewardDate)
        return "KEY_AwardOpenerLastRewardDate";
    if (keyId == KEY_AwardToughy)
        return "KEY_AwardToughy";
    if (keyId == KEY_AwardToughyLastRewardDate)
        return "KEY_AwardToughyLastRewardDate";
    if (keyId == KEY_AwardInvincibleFury)
        return "KEY_AwardInvincibleFury";
    if (keyId == KEY_AwardInvincibleFuryLastRewardDate)
        return "KEY_AwardInvincibleFuryLastRewardDate";
    if (keyId == KEY_AwardOculist)
        return "KEY_AwardOculist";
    if (keyId == KEY_AwardOculistLastRewardDate)
        return "KEY_AwardOculistLastRewardDate";
    if (keyId == KEY_AwardLightingReflexes)
        return "KEY_AwardLightingReflexes";
    if (keyId == KEY_AwardLightingReflexesLastRewardDate)
        return "KEY_AwardLightingReflexesLastRewardDate";
    if (keyId == KEY_AwardSprinterStopper)
        return "KEY_AwardSprinterStopper";
    if (keyId == KEY_AwardSprinterStopperLastRewardDate)
        return "KEY_AwardSprinterStopperLastRewardDate";
    if (keyId == KEY_AwardMarksMan)
        return "KEY_AwardMarksMan";
    if (keyId == KEY_AwardMarksManLastRewardDate)
        return "KEY_AwardMarksManLastRewardDate";
    if (keyId == KEY_AwardPeaceAmbassador)
        return "KEY_AwardPeaceAmbassador";
    if (keyId == KEY_AwardPeaceAmbassadorLastRewardDate)
        return "KEY_AwardPeaceAmbassadorLastRewardDate";
    if (keyId == KEY_AwardDeadlyAccuracy)
        return "KEY_AwardDeadlyAccuracy";
    if (keyId == KEY_AwardDeadlyAccuracyLastRewardDate)
        return "KEY_AwardDeadlyAccuracyLastRewardDate";
    if (keyId == KEY_AwardRemembrance)
        return "KEY_AwardRemembrance";
    if (keyId == KEY_AwardRemembranceLastRewardDate)
        return "KEY_AwardRemembranceLastRewardDate";
    if (keyId == KEY_AwardAvenger)
        return "KEY_AwardAvenger";
    if (keyId == KEY_AwardAvengerLastRewardDate)
        return "KEY_AwardAvengerLastRewardDate";
    if (keyId == KEY_AwardCherub)
        return "KEY_AwardCherub";
    if (keyId == KEY_AwardCherubLastRewardDate)
        return "KEY_AwardCherubLastRewardDate";
    if (keyId == KEY_AwardDignity)
        return "KEY_AwardDignity";
    if (keyId == KEY_AwardDignityLastRewardDate)
        return "KEY_AwardDignityLastRewardDate";
    if (keyId == KEY_AwardStalkerFlair)
        return "KEY_AwardStalkerFlair";
    if (keyId == KEY_AwardStalkerFlairLastRewardDate)
        return "KEY_AwardStalkerFlairLastRewardDate";
    if (keyId == KEY_AwardLucky)
        return "KEY_AwardLucky";
    if (keyId == KEY_AwardLuckyLastRewardDate)
        return "KEY_AwardLuckyLastRewardDate";
    if (keyId == KEY_AwardBlackList)
        return "KEY_AwardBlackList";
    if (keyId == KEY_AwardBlackListLastRewardDate)
        return "KEY_AwardBlackListLastRewardDate";
    if (keyId == KEY_AwardSilentDeath)
        return "KEY_AwardSilentDeath";
    if (keyId == KEY_AwardSilentDeathLastRewardDate)
        return "KEY_AwardSilentDeathLastRewardDate";
    if (keyId == KEY_PlayerName)
        return "KEY_PlayerName";

    return "";
}

int ATLAS_GET_STAT(char* statName)
{
    if (!statName)
        return 0;

    if (!xr_strcmp("STAT_AwardAchillesHeel", statName))
        return STAT_AwardAchillesHeel;
    if (!xr_strcmp("STAT_AwardAchillesHeelLastRewardDate", statName))
        return STAT_AwardAchillesHeelLastRewardDate;
    if (!xr_strcmp("STAT_AwardAvenger", statName))
        return STAT_AwardAvenger;
    if (!xr_strcmp("STAT_AwardAvengerLastRewardDate", statName))
        return STAT_AwardAvengerLastRewardDate;
    if (!xr_strcmp("STAT_AwardBlackList", statName))
        return STAT_AwardBlackList;
    if (!xr_strcmp("STAT_AwardBlackListLastRewardDate", statName))
        return STAT_AwardBlackListLastRewardDate;
    if (!xr_strcmp("STAT_AwardBlitzkrieg", statName))
        return STAT_AwardBlitzkrieg;
    if (!xr_strcmp("STAT_AwardBlitzkriegLastRewardDate", statName))
        return STAT_AwardBlitzkriegLastRewardDate;
    if (!xr_strcmp("STAT_AwardCherub", statName))
        return STAT_AwardCherub;
    if (!xr_strcmp("STAT_AwardCherubLastRewardDate", statName))
        return STAT_AwardCherubLastRewardDate;
    if (!xr_strcmp("STAT_AwardClimber", statName))
        return STAT_AwardClimber;
    if (!xr_strcmp("STAT_AwardClimberLastRewardDate", statName))
        return STAT_AwardClimberLastRewardDate;
    if (!xr_strcmp("STAT_AwardDeadlyAccuracy", statName))
        return STAT_AwardDeadlyAccuracy;
    if (!xr_strcmp("STAT_AwardDeadlyAccuracyLastRewardDate", statName))
        return STAT_AwardDeadlyAccuracyLastRewardDate;
    if (!xr_strcmp("STAT_AwardDignity", statName))
        return STAT_AwardDignity;
    if (!xr_strcmp("STAT_AwardDignityLastRewardDate", statName))
        return STAT_AwardDignityLastRewardDate;
    if (!xr_strcmp("STAT_AwardDoubleShotDoubleKill", statName))
        return STAT_AwardDoubleShotDoubleKill;
    if (!xr_strcmp("STAT_AwardDoubleShotDoubleKillLastRewardDate", statName))
        return STAT_AwardDoubleShotDoubleKillLastRewardDate;
    if (!xr_strcmp("STAT_AwardDryVictory", statName))
        return STAT_AwardDryVictory;
    if (!xr_strcmp("STAT_AwardDryVictoryLastRewardDate", statName))
        return STAT_AwardDryVictoryLastRewardDate;
    if (!xr_strcmp("STAT_AwardFasterThanBullets", statName))
        return STAT_AwardFasterThanBullets;
    if (!xr_strcmp("STAT_AwardFasterThanBulletsLastRewardDate", statName))
        return STAT_AwardFasterThanBulletsLastRewardDate;
    if (!xr_strcmp("STAT_AwardHarvestTime", statName))
        return STAT_AwardHarvestTime;
    if (!xr_strcmp("STAT_AwardHarvestTimeLastRewardDate", statName))
        return STAT_AwardHarvestTimeLastRewardDate;
    if (!xr_strcmp("STAT_AwardInvincibleFury", statName))
        return STAT_AwardInvincibleFury;
    if (!xr_strcmp("STAT_AwardInvincibleFuryLastRewardDate", statName))
        return STAT_AwardInvincibleFuryLastRewardDate;
    if (!xr_strcmp("STAT_AwardLightingReflexes", statName))
        return STAT_AwardLightingReflexes;
    if (!xr_strcmp("STAT_AwardLightingReflexesLastRewardDate", statName))
        return STAT_AwardLightingReflexesLastRewardDate;
    if (!xr_strcmp("STAT_AwardLucky", statName))
        return STAT_AwardLucky;
    if (!xr_strcmp("STAT_AwardLuckyLastRewardDate", statName))
        return STAT_AwardLuckyLastRewardDate;
    if (!xr_strcmp("STAT_AwardMad", statName))
        return STAT_AwardMad;
    if (!xr_strcmp("STAT_AwardMadLastRewardDate", statName))
        return STAT_AwardMadLastRewardDate;
    if (!xr_strcmp("STAT_AwardMarksman", statName))
        return STAT_AwardMarksman;
    if (!xr_strcmp("STAT_AwardMarksmanLastRewardDate", statName))
        return STAT_AwardMarksmanLastRewardDate;
    if (!xr_strcmp("STAT_AwardMasscare", statName))
        return STAT_AwardMasscare;
    if (!xr_strcmp("STAT_AwardMasscareLastRewardDate", statName))
        return STAT_AwardMasscareLastRewardDate;
    if (!xr_strcmp("STAT_AwardMultichampion", statName))
        return STAT_AwardMultichampion;
    if (!xr_strcmp("STAT_AwardMultichampionLastRewardDate", statName))
        return STAT_AwardMultichampionLastRewardDate;
    if (!xr_strcmp("STAT_AwardOculist", statName))
        return STAT_AwardOculist;
    if (!xr_strcmp("STAT_AwardOculistLastRewardDate", statName))
        return STAT_AwardOculistLastRewardDate;
    if (!xr_strcmp("STAT_AwardOpener", statName))
        return STAT_AwardOpener;
    if (!xr_strcmp("STAT_AwardOpenerLastRewardDate", statName))
        return STAT_AwardOpenerLastRewardDate;
    if (!xr_strcmp("STAT_AwardOwerwhelmingSuperiority", statName))
        return STAT_AwardOwerwhelmingSuperiority;
    if (!xr_strcmp("STAT_AwardOwerwhelmingSuperiorityLastRewardDate", statName))
        return STAT_AwardOwerwhelmingSuperiorityLastRewardDate;
    if (!xr_strcmp("STAT_AwardParanoia", statName))
        return STAT_AwardParanoia;
    if (!xr_strcmp("STAT_AwardParanoiaLastRewardDate", statName))
        return STAT_AwardParanoiaLastRewardDate;
    if (!xr_strcmp("STAT_AwardPeaceAmbassador", statName))
        return STAT_AwardPeaceAmbassador;
    if (!xr_strcmp("STAT_AwardPeaceAmbassadorLastRewardDate", statName))
        return STAT_AwardPeaceAmbassadorLastRewardDate;
    if (!xr_strcmp("STAT_AwardRemembrance", statName))
        return STAT_AwardRemembrance;
    if (!xr_strcmp("STAT_AwardRemembranceLastRewardDate", statName))
        return STAT_AwardRemembranceLastRewardDate;
    if (!xr_strcmp("STAT_AwardSilentDeath", statName))
        return STAT_AwardSilentDeath;
    if (!xr_strcmp("STAT_AwardSilentDeathLastRewardDate", statName))
        return STAT_AwardSilentDeathLastRewardDate;
    if (!xr_strcmp("STAT_AwardSkewer", statName))
        return STAT_AwardSkewer;
    if (!xr_strcmp("STAT_AwardSkewerLastRewardDate", statName))
        return STAT_AwardSkewerLastRewardDate;
    if (!xr_strcmp("STAT_AwardSprinterStopper", statName))
        return STAT_AwardSprinterStopper;
    if (!xr_strcmp("STAT_AwardSprinterStopperLastRewardDate", statName))
        return STAT_AwardSprinterStopperLastRewardDate;
    if (!xr_strcmp("STAT_AwardStalkerFlair", statName))
        return STAT_AwardStalkerFlair;
    if (!xr_strcmp("STAT_AwardStalkerFlairLastRewardDate", statName))
        return STAT_AwardStalkerFlairLastRewardDate;
    if (!xr_strcmp("STAT_AwardToughy", statName))
        return STAT_AwardToughy;
    if (!xr_strcmp("STAT_AwardToughyLastRewardDate", statName))
        return STAT_AwardToughyLastRewardDate;
    if (!xr_strcmp("STAT_BestScore_BackstabsKillsInRow", statName))
        return STAT_BestScore_BackstabsKillsInRow;
    if (!xr_strcmp("STAT_BestScore_BleedKillsInRow", statName))
        return STAT_BestScore_BleedKillsInRow;
    if (!xr_strcmp("STAT_BestScore_ExplosiveKillsInRow", statName))
        return STAT_BestScore_ExplosiveKillsInRow;
    if (!xr_strcmp("STAT_BestScore_EyeKillsInRow", statName))
        return STAT_BestScore_EyeKillsInRow;
    if (!xr_strcmp("STAT_BestScore_HeadshotsKillsInRow", statName))
        return STAT_BestScore_HeadshotsKillsInRow;
    if (!xr_strcmp("STAT_BestScore_KillsInRow", statName))
        return STAT_BestScore_KillsInRow;
    if (!xr_strcmp("STAT_BestScore_KnifeKillsInRow", statName))
        return STAT_BestScore_KnifeKillsInRow;
    if (!xr_strcmp("STAT_PlayerName", statName))
        return STAT_PlayerName;

    return 0;
}
char* ATLAS_GET_STAT_NAME(int statId)
{
    if (statId <= 0)
        return "";

    if (statId == STAT_AwardAchillesHeel)
        return "STAT_AwardAchillesHeel";
    if (statId == STAT_AwardAchillesHeelLastRewardDate)
        return "STAT_AwardAchillesHeelLastRewardDate";
    if (statId == STAT_AwardAvenger)
        return "STAT_AwardAvenger";
    if (statId == STAT_AwardAvengerLastRewardDate)
        return "STAT_AwardAvengerLastRewardDate";
    if (statId == STAT_AwardBlackList)
        return "STAT_AwardBlackList";
    if (statId == STAT_AwardBlackListLastRewardDate)
        return "STAT_AwardBlackListLastRewardDate";
    if (statId == STAT_AwardBlitzkrieg)
        return "STAT_AwardBlitzkrieg";
    if (statId == STAT_AwardBlitzkriegLastRewardDate)
        return "STAT_AwardBlitzkriegLastRewardDate";
    if (statId == STAT_AwardCherub)
        return "STAT_AwardCherub";
    if (statId == STAT_AwardCherubLastRewardDate)
        return "STAT_AwardCherubLastRewardDate";
    if (statId == STAT_AwardClimber)
        return "STAT_AwardClimber";
    if (statId == STAT_AwardClimberLastRewardDate)
        return "STAT_AwardClimberLastRewardDate";
    if (statId == STAT_AwardDeadlyAccuracy)
        return "STAT_AwardDeadlyAccuracy";
    if (statId == STAT_AwardDeadlyAccuracyLastRewardDate)
        return "STAT_AwardDeadlyAccuracyLastRewardDate";
    if (statId == STAT_AwardDignity)
        return "STAT_AwardDignity";
    if (statId == STAT_AwardDignityLastRewardDate)
        return "STAT_AwardDignityLastRewardDate";
    if (statId == STAT_AwardDoubleShotDoubleKill)
        return "STAT_AwardDoubleShotDoubleKill";
    if (statId == STAT_AwardDoubleShotDoubleKillLastRewardDate)
        return "STAT_AwardDoubleShotDoubleKillLastRewardDate";
    if (statId == STAT_AwardDryVictory)
        return "STAT_AwardDryVictory";
    if (statId == STAT_AwardDryVictoryLastRewardDate)
        return "STAT_AwardDryVictoryLastRewardDate";
    if (statId == STAT_AwardFasterThanBullets)
        return "STAT_AwardFasterThanBullets";
    if (statId == STAT_AwardFasterThanBulletsLastRewardDate)
        return "STAT_AwardFasterThanBulletsLastRewardDate";
    if (statId == STAT_AwardHarvestTime)
        return "STAT_AwardHarvestTime";
    if (statId == STAT_AwardHarvestTimeLastRewardDate)
        return "STAT_AwardHarvestTimeLastRewardDate";
    if (statId == STAT_AwardInvincibleFury)
        return "STAT_AwardInvincibleFury";
    if (statId == STAT_AwardInvincibleFuryLastRewardDate)
        return "STAT_AwardInvincibleFuryLastRewardDate";
    if (statId == STAT_AwardLightingReflexes)
        return "STAT_AwardLightingReflexes";
    if (statId == STAT_AwardLightingReflexesLastRewardDate)
        return "STAT_AwardLightingReflexesLastRewardDate";
    if (statId == STAT_AwardLucky)
        return "STAT_AwardLucky";
    if (statId == STAT_AwardLuckyLastRewardDate)
        return "STAT_AwardLuckyLastRewardDate";
    if (statId == STAT_AwardMad)
        return "STAT_AwardMad";
    if (statId == STAT_AwardMadLastRewardDate)
        return "STAT_AwardMadLastRewardDate";
    if (statId == STAT_AwardMarksman)
        return "STAT_AwardMarksman";
    if (statId == STAT_AwardMarksmanLastRewardDate)
        return "STAT_AwardMarksmanLastRewardDate";
    if (statId == STAT_AwardMasscare)
        return "STAT_AwardMasscare";
    if (statId == STAT_AwardMasscareLastRewardDate)
        return "STAT_AwardMasscareLastRewardDate";
    if (statId == STAT_AwardMultichampion)
        return "STAT_AwardMultichampion";
    if (statId == STAT_AwardMultichampionLastRewardDate)
        return "STAT_AwardMultichampionLastRewardDate";
    if (statId == STAT_AwardOculist)
        return "STAT_AwardOculist";
    if (statId == STAT_AwardOculistLastRewardDate)
        return "STAT_AwardOculistLastRewardDate";
    if (statId == STAT_AwardOpener)
        return "STAT_AwardOpener";
    if (statId == STAT_AwardOpenerLastRewardDate)
        return "STAT_AwardOpenerLastRewardDate";
    if (statId == STAT_AwardOwerwhelmingSuperiority)
        return "STAT_AwardOwerwhelmingSuperiority";
    if (statId == STAT_AwardOwerwhelmingSuperiorityLastRewardDate)
        return "STAT_AwardOwerwhelmingSuperiorityLastRewardDate";
    if (statId == STAT_AwardParanoia)
        return "STAT_AwardParanoia";
    if (statId == STAT_AwardParanoiaLastRewardDate)
        return "STAT_AwardParanoiaLastRewardDate";
    if (statId == STAT_AwardPeaceAmbassador)
        return "STAT_AwardPeaceAmbassador";
    if (statId == STAT_AwardPeaceAmbassadorLastRewardDate)
        return "STAT_AwardPeaceAmbassadorLastRewardDate";
    if (statId == STAT_AwardRemembrance)
        return "STAT_AwardRemembrance";
    if (statId == STAT_AwardRemembranceLastRewardDate)
        return "STAT_AwardRemembranceLastRewardDate";
    if (statId == STAT_AwardSilentDeath)
        return "STAT_AwardSilentDeath";
    if (statId == STAT_AwardSilentDeathLastRewardDate)
        return "STAT_AwardSilentDeathLastRewardDate";
    if (statId == STAT_AwardSkewer)
        return "STAT_AwardSkewer";
    if (statId == STAT_AwardSkewerLastRewardDate)
        return "STAT_AwardSkewerLastRewardDate";
    if (statId == STAT_AwardSprinterStopper)
        return "STAT_AwardSprinterStopper";
    if (statId == STAT_AwardSprinterStopperLastRewardDate)
        return "STAT_AwardSprinterStopperLastRewardDate";
    if (statId == STAT_AwardStalkerFlair)
        return "STAT_AwardStalkerFlair";
    if (statId == STAT_AwardStalkerFlairLastRewardDate)
        return "STAT_AwardStalkerFlairLastRewardDate";
    if (statId == STAT_AwardToughy)
        return "STAT_AwardToughy";
    if (statId == STAT_AwardToughyLastRewardDate)
        return "STAT_AwardToughyLastRewardDate";
    if (statId == STAT_BestScore_BackstabsKillsInRow)
        return "STAT_BestScore_BackstabsKillsInRow";
    if (statId == STAT_BestScore_BleedKillsInRow)
        return "STAT_BestScore_BleedKillsInRow";
    if (statId == STAT_BestScore_ExplosiveKillsInRow)
        return "STAT_BestScore_ExplosiveKillsInRow";
    if (statId == STAT_BestScore_EyeKillsInRow)
        return "STAT_BestScore_EyeKillsInRow";
    if (statId == STAT_BestScore_HeadshotsKillsInRow)
        return "STAT_BestScore_HeadshotsKillsInRow";
    if (statId == STAT_BestScore_KillsInRow)
        return "STAT_BestScore_KillsInRow";
    if (statId == STAT_BestScore_KnifeKillsInRow)
        return "STAT_BestScore_KnifeKillsInRow";
    if (statId == STAT_PlayerName)
        return "STAT_PlayerName";

    return "";
}

int ATLAS_GET_STAT_PAGE_BY_ID(int statId)
{
    if (statId <= 0)
        return 0;

    // PlayerStats
    if (statId == 1 || statId == 2 || statId == 3 || statId == 4 || statId == 5 || statId == 6 || statId == 7 ||
    statId == 8 || statId == 9 || statId == 10 || statId == 11 || statId == 12 || statId == 13 || statId == 14 ||
    statId == 15 || statId == 16 || statId == 17 || statId == 18 || statId == 19 || statId == 20 || statId == 21 ||
    statId == 22 || statId == 23 || statId == 24 || statId == 25 || statId == 26 || statId == 27 || statId == 28 ||
    statId == 29 || statId == 30 || statId == 31 || statId == 32 || statId == 33 || statId == 34 || statId == 35 ||
    statId == 36 || statId == 37 || statId == 38 || statId == 39 || statId == 40 || statId == 41 || statId == 42 ||
    statId == 43 || statId == 44 || statId == 45 || statId == 46 || statId == 47 || statId == 48 || statId == 49 ||
    statId == 50 || statId == 51 || statId == 52 || statId == 53 || statId == 54 || statId == 55 || statId == 56 ||
    statId == 57 || statId == 58 || statId == 59 || statId == 60 || statId == 61 || statId == 62 || statId == 63 ||
    statId == 64 || statId == 65 || statId == 66 || statId == 67 || statId == 68)
        return 1;

    return 0;
}

int ATLAS_GET_STAT_PAGE_BY_NAME(char* statName)
{
    if (!statName)
        return 0;

    // PlayerStats
    if (!xr_strcmp("STAT_AwardAchillesHeel", statName) || !xr_strcmp("STAT_AwardAchillesHeelLastRewardDate", statName) ||
    !xr_strcmp("STAT_AwardAvenger", statName) || !xr_strcmp("STAT_AwardAvengerLastRewardDate", statName) ||
    !xr_strcmp("STAT_AwardBlackList", statName) || !xr_strcmp("STAT_AwardBlackListLastRewardDate", statName) ||
    !xr_strcmp("STAT_AwardBlitzkrieg", statName) || !xr_strcmp("STAT_AwardBlitzkriegLastRewardDate", statName) ||
    !xr_strcmp("STAT_AwardCherub", statName) || !xr_strcmp("STAT_AwardCherubLastRewardDate", statName) ||
    !xr_strcmp("STAT_AwardClimber", statName) || !xr_strcmp("STAT_AwardClimberLastRewardDate", statName) ||
    !xr_strcmp("STAT_AwardDeadlyAccuracy", statName) || !xr_strcmp("STAT_AwardDeadlyAccuracyLastRewardDate", statName) ||
    !xr_strcmp("STAT_AwardDignity", statName) || !xr_strcmp("STAT_AwardDignityLastRewardDate", statName) ||
    !xr_strcmp("STAT_AwardDoubleShotDoubleKill", statName) ||
    !xr_strcmp("STAT_AwardDoubleShotDoubleKillLastRewardDate", statName) || !xr_strcmp("STAT_AwardDryVictory", statName) ||
    !xr_strcmp("STAT_AwardDryVictoryLastRewardDate", statName) || !xr_strcmp("STAT_AwardFasterThanBullets", statName) ||
    !xr_strcmp("STAT_AwardFasterThanBulletsLastRewardDate", statName) || !xr_strcmp("STAT_AwardHarvestTime", statName) ||
    !xr_strcmp("STAT_AwardHarvestTimeLastRewardDate", statName) || !xr_strcmp("STAT_AwardInvincibleFury", statName) ||
    !xr_strcmp("STAT_AwardInvincibleFuryLastRewardDate", statName) || !xr_strcmp("STAT_AwardLightingReflexes", statName) ||
    !xr_strcmp("STAT_AwardLightingReflexesLastRewardDate", statName) || !xr_strcmp("STAT_AwardLucky", statName) ||
    !xr_strcmp("STAT_AwardLuckyLastRewardDate", statName) || !xr_strcmp("STAT_AwardMad", statName) ||
    !xr_strcmp("STAT_AwardMadLastRewardDate", statName) || !xr_strcmp("STAT_AwardMarksman", statName) ||
    !xr_strcmp("STAT_AwardMarksmanLastRewardDate", statName) || !xr_strcmp("STAT_AwardMasscare", statName) ||
    !xr_strcmp("STAT_AwardMasscareLastRewardDate", statName) || !xr_strcmp("STAT_AwardMultichampion", statName) ||
    !xr_strcmp("STAT_AwardMultichampionLastRewardDate", statName) || !xr_strcmp("STAT_AwardOculist", statName) ||
    !xr_strcmp("STAT_AwardOculistLastRewardDate", statName) || !xr_strcmp("STAT_AwardOpener", statName) ||
    !xr_strcmp("STAT_AwardOpenerLastRewardDate", statName) || !xr_strcmp("STAT_AwardOwerwhelmingSuperiority", statName) ||
    !xr_strcmp("STAT_AwardOwerwhelmingSuperiorityLastRewardDate", statName) || !xr_strcmp("STAT_AwardParanoia", statName) ||
    !xr_strcmp("STAT_AwardParanoiaLastRewardDate", statName) || !xr_strcmp("STAT_AwardPeaceAmbassador", statName) ||
    !xr_strcmp("STAT_AwardPeaceAmbassadorLastRewardDate", statName) || !xr_strcmp("STAT_AwardRemembrance", statName) ||
    !xr_strcmp("STAT_AwardRemembranceLastRewardDate", statName) || !xr_strcmp("STAT_AwardSilentDeath", statName) ||
    !xr_strcmp("STAT_AwardSilentDeathLastRewardDate", statName) || !xr_strcmp("STAT_AwardSkewer", statName) ||
    !xr_strcmp("STAT_AwardSkewerLastRewardDate", statName) || !xr_strcmp("STAT_AwardSprinterStopper", statName) ||
    !xr_strcmp("STAT_AwardSprinterStopperLastRewardDate", statName) || !xr_strcmp("STAT_AwardStalkerFlair", statName) ||
    !xr_strcmp("STAT_AwardStalkerFlairLastRewardDate", statName) || !xr_strcmp("STAT_AwardToughy", statName) ||
    !xr_strcmp("STAT_AwardToughyLastRewardDate", statName) || !xr_strcmp("STAT_BestScore_BackstabsKillsInRow", statName) ||
    !xr_strcmp("STAT_BestScore_BleedKillsInRow", statName) || !xr_strcmp("STAT_BestScore_ExplosiveKillsInRow", statName) ||
    !xr_strcmp("STAT_BestScore_EyeKillsInRow", statName) || !xr_strcmp("STAT_BestScore_HeadshotsKillsInRow", statName) ||
    !xr_strcmp("STAT_BestScore_KillsInRow", statName) || !xr_strcmp("STAT_BestScore_KnifeKillsInRow", statName) ||
    !xr_strcmp("STAT_PlayerName", statName))
        return 1;

    return 0;
}
