NVAPI Reference Documentation
NVAPI Reference Documentation
NVIDIA
Release 337: May 2
2014
nvHLSLExtns.h File Reference
#include "nvHLSLExtnsInternal.h"
Functions
int NvShfl (int val, uint srcLane, int width=NV_WARP_SIZE)
int NvShflUp (int val, uint delta, int width=NV_WARP_SIZE)
int NvShflDown (int val, uint delta, int width=NV_WARP_SIZE)
int NvShflXor (int val, uint laneMask, int width=NV_WARP_SIZE)
uint NvAny (int predicate)
uint NvAll (int predicate)
uint NvBallot (int predicate)
int NvGetLaneId ()
Function Documentation
uint NvAll (int predicate)
References g_NvidiaExt, and NV_EXTN_OP_VOTE_ALL.
uint NvAny (int predicate)
References g_NvidiaExt, and NV_EXTN_OP_VOTE_ANY.
uint NvBallot (int predicate)
References g_NvidiaExt, and NV_EXTN_OP_VOTE_BALLOT.
int NvGetLaneId ()
References g_NvidiaExt, and NV_EXTN_OP_GET_LANE_ID.
int NvShfl (int val, uint srcLane, int width = NV_WARP_SIZE)
References __NvGetShflMaskFromWidth(), g_NvidiaExt, and NV_EXTN_OP_SHFL.
int NvShflDown (int val, uint delta, int width = NV_WARP_SIZE)
References __NvGetShflMaskFromWidth(), g_NvidiaExt, and NV_EXTN_OP_SHFL_DOWN.
int NvShflUp (int val, uint delta, int width = NV_WARP_SIZE)
References g_NvidiaExt, NV_EXTN_OP_SHFL_UP, and NV_WARP_SIZE.
int NvShflXor (int val, uint laneMask, int width = NV_WARP_SIZE)
References __NvGetShflMaskFromWidth(), g_NvidiaExt, and NV_EXTN_OP_SHFL_XOR.
Copyright (c) 2007-2014 NVIDIA Corporation. All rights reserved.